name: fig_serv_example
description: A sample fig auth app
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.4
  fig_auth: any
  fig_proto: any
  logging: ^1.2.0
  openid_client: ^0.4.8

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^2.0.0
  test: ^1.21.0