name: fig_auth
description: GRPC Server Authentication Framework using Firebase Authentication
version: 0.0.1
repository: https://github.com/wstrange/fig

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.4
  logging: ^1.2.0
  openid_client: ^0.4.8
  json_annotation: ^4.8.1
  drift: ^2.14.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  drift_dev: ^2.14.1
