// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefvHfdcal2ns3wtrxaBCvPyNM5HVEE50',
    appId: '1:465372895035:web:8e196854177b3fb4ab891e',
    messagingSenderId: '465372895035',
    projectId: 'aclub-67a12',
    authDomain: 'aclub-67a12.firebaseapp.com',
    storageBucket: 'aclub-67a12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGE6TL83miL9Q-8dHrFi6EClK3oz9V3ug',
    appId: '1:465372895035:android:5df5371ab0c94daeab891e',
    messagingSenderId: '465372895035',
    projectId: 'aclub-67a12',
    storageBucket: 'aclub-67a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGDGg1jbyvDKpW0fr5GWgm2DFZscE_S0o',
    appId: '1:465372895035:ios:87c706a58585d5d6ab891e',
    messagingSenderId: '465372895035',
    projectId: 'aclub-67a12',
    storageBucket: 'aclub-67a12.appspot.com',
    androidClientId: '465372895035-3a1u99801t7q18n11ob2ohjss0ma1n1k.apps.googleusercontent.com',
    iosClientId: '465372895035-fspu9s0nlsebf111nbmkn3v3ngnl8qe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGDGg1jbyvDKpW0fr5GWgm2DFZscE_S0o',
    appId: '1:465372895035:ios:93fe8575768fd460ab891e',
    messagingSenderId: '465372895035',
    projectId: 'aclub-67a12',
    storageBucket: 'aclub-67a12.appspot.com',
    androidClientId: '465372895035-3a1u99801t7q18n11ob2ohjss0ma1n1k.apps.googleusercontent.com',
    iosClientId: '465372895035-e8qimd20cujov1rls9l1n3e7hkrd3bcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
