name: fig_proto
description: Protobuf and grpc definistions for fig
version: 1.0.0
repository: https://github.com/wstrange/fig
publish_to: none

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
